### ISSUE TITLE
Document how to use metric-store with Grafana

### ISSUE THREAD

**Issue by tlwr** [cloudfoundry/metric-store-release#38]
### Is this an Issue/Bug or a Feature Request?

[ ] Issue or Bug
[x] Feature Request

### What is this issue about? Or why do you want this feature?

I had to ask in CF Slack and do some Github code search in order to configure metric-store to work with Grafana

##### What version of Metric Store are you using?

1.1.2

---

I'm raising this issue to assign to myself, where would be a good place to document this, that isn't this issue? I'll then raise a PR.

---

⬇️ Operation to create an UAA OAuth client for Grafana

```
- type: replace
  path: /variables/-
  value:
    name: grafana_client_secret
    type: password

- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/grafana?
  value:
    authorities: ''
    scope: openid,uaa.resource,doppler.firehose,logs.admin,cloud_controller.read
    authorized-grant-types: authorization_code,refresh_token
    override: true
    secret: ((grafana_client_secret))
    redirect-uri: https://grafana.((system_domain))/login/generic_oauth
```

⬇️ Operation to create Grafana with the correct configuration

```
- type: replace
  path: /instance_groups/name=metric-store/jobs/-
  value:
    name: grafana
    release: grafana
    properties:
      grafana:
        root_url: https://grafana.((system_domain))
        users:
          auto_assign_organization_role: Admin
        auth:
          generic_oauth:
            name: GOV.UK PaaS
            enabled: true
            allow_sign_up: true
            client_id: grafana
            client_secret: ((grafana_client_secret))

            scopes:
              - openid
              - uaa.resource
              - doppler.firehose
              - logs.admin
              - cloud_controller.read

            auth_url: https://login.((system_domain))/oauth/authorize
            token_url: https://login.((system_domain))/oauth/token
            api_url: https://login.((system_domain))/userinfo
        datasources:
          - name: Prometheus
            url: https://metric-store.((system_domain))
            type: prometheus
            editable: false
            orgId: 1
            jsonData: '{"httpMethod":"GET","keepCookies":[],"oauthPassThru":true}'

```
